# Generated by Django 2.2 on 2020-05-17 17:16

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20200517_2124'),
        ('workflowengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='stage',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
        migrations.AddField(
            model_name='form',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
        migrations.AddField(
            model_name='workflowtype',
            name='start_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
