# Generated by Django 2.2.4 on 2019-08-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0002_case_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
