# Generated by Django 2.2.4 on 2019-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0002_auto_20190826_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restriction_pin',
            field=models.CharField(default=12345, max_length=128, verbose_name='restriction_pin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='restricted',
            field=models.BooleanField(default=True),
        ),
    ]
