# Generated by Django 2.2.4 on 2019-08-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('workflowengine', '0003_auto_20190817_0532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Flow',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='case',
            new_name='flow',
        ),
    ]
