# Generated by Django 2.2.4 on 2019-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0003_auto_20190826_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(max_length=20)),
                ('trigger_sequence', models.IntegerField()),
            ],
        ),
    ]
