# Generated by Django 2.2.4 on 2019-08-18 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('workflowengine', '0004_auto_20190817_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_description', models.CharField(default='', max_length=200)),
                ('field_question', models.CharField(default='', max_length=300)),
                ('field_display', models.CharField(choices=[('NONE', 'NONE'), ('FULLDATE', 'FULLDATE'), ('DATE', 'DATE'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE')], default='NONE', max_length=20)),
                ('multichoice_options', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='form',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowengine.Flow'),
        ),
        migrations.AddField(
            model_name='form',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
