# Generated by Django 2.2.4 on 2019-08-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0004_workflowtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflowengine.WorkflowType'),
        ),
    ]
