# Generated by Django 2.2.4 on 2019-08-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('workflowengine', '0005_flow_flow_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtype',
            name='trigger_sequence',
        ),
        migrations.AddField(
            model_name='flow',
            name='parent_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowengine.Flow'),
        ),
        migrations.AddField(
            model_name='workflowtype',
            name='start_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
