# Generated by Django 2.2.4 on 2019-08-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0006_formfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilePhoto',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LONG_TEXT', 'LONG_TEXT'), ('DATE', 'DATE'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowengine.UserRole'),
        ),
    ]
