# Generated by Django 2.2.4 on 2019-08-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0006_auto_20190827_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflow',
            name='creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LONG_TEXT', 'LONG_TEXT'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE'), ('RADIO', 'RADIO'), ('FILE', 'FILE'), ('CHILD_FLOW_CREATION_BUTTON', 'CHILD_FLOW_CREATION_BUTTON')], default='TEXT', max_length=20),
        ),
    ]
