# Generated by Django 2.2.4 on 2019-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0007_auto_20190827_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
