# Generated by Django 2.2.4 on 2019-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0007_auto_20190820_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
