# Generated by Django 2.2.4 on 2019-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0008_flow_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtype',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
