# Generated by Django 2.2.4 on 2019-08-20 11:54

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0009_remove_form_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='stage',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
    ]
