# Generated by Django 2.2.4 on 2019-09-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0009_workflowtype_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
