# Generated by Django 2.2.4 on 2019-08-20 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0010_auto_20190820_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='Role',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='user',
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowengine.Flow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
