# Generated by Django 2.2.4 on 2019-09-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0010_role_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
