# Generated by Django 2.2.4 on 2019-08-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0011_auto_20190820_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='multichoice_options',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
