# Generated by Django 2.2.4 on 2019-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0011_role_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
