# Generated by Django 2.2.4 on 2019-08-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0012_auto_20190820_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_display',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('FULLDATE', 'FULLDATE'), ('FULLDATE_TEXT_MONTH', 'FULLDATE_TEXT_MONTH'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LONG_TEXT', 'LONG_TEXT'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE')], default='TEXT', max_length=20),
        ),
    ]
