# Generated by Django 2.2.4 on 2019-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0012_expert_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restriction_pin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='restriction_pin'),
        ),
    ]
