# Generated by Django 2.2.4 on 2019-09-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0013_auto_20190906_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
