# Generated by Django 2.2.4 on 2019-08-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0014_auto_20190821_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_display',
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_question',
        ),
        migrations.AddField(
            model_name='field',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='field',
            name='question',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LONG_TEXT', 'LONG_TEXT'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE'), ('RADIO', 'RADIO'), ('FILE', 'FILE')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='multichoice_options',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
