# Generated by Django 2.2.4 on 2019-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0015_auto_20190821_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='field',
            name='question',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
