# Generated by Django 2.2.4 on 2019-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0015_auto_20190906_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('LONG_TEXT', 'LONG_TEXT'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('CHECK_BOX', 'CHECK_BOX'), ('MULTICHOICE', 'MULTICHOICE'), ('RADIO', 'RADIO'), ('FILE', 'FILE'), ('CHILD_FLOW_CREATION_BUTTON', 'CHILD_FLOW_CREATION_BUTTON'), ('MESSAGE_PROCESS', 'MESSAGE_PROCESS'), ('SECTION_SEPERATOR', 'SECTION_SEPERATOR'), ('HIDDEN', 'HIDDEN'), ('LOCATION', 'LOCATION'), ('SKIP_STEP_BUTTON', 'SKIP_STEP_BUTTON'), ('API_DATA_DROPDOWN', 'API_DATA_DROPDOWN')], default='TEXT', max_length=40),
        ),
    ]
