# Generated by Django 2.2.4 on 2019-09-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0016_auto_20190906_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='flow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflowengine.WorkflowType'),
        ),
    ]
