# Generated by Django 2.2.4 on 2019-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowengine', '0016_auto_20190821_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
