# Generated by Django 2.2.4 on 2019-08-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('workflowengine', '0017_formfield_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formfield',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State'),
        ),
    ]
