# Generated by Django 2.2.4 on 2019-08-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
        ('workflowengine', '0021_auto_20190821_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field', 'stage')},
        ),
    ]
